version: '3.8'

services:
  api:
    build:
      context: ./ScreenSound.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=screensound;user=root;password=senha123;

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: screensound
      MYSQL_ROOT_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
